env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  update_milestone:
    name: Update milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context);

      - uses: actions/checkout@v3

      - uses: ./.github/actions/on_milestone
        env:
          milestone: ${{ toJSON(github.event) }}

name: On milestone
on: milestone
