jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm install
      - run: npm run test
name: On pull request
on:
  pull_request:
    branches:
      - master
