jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: npm install
      - run: npm run test
  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: npm install
      - run: npm run build
      - run: npm version patch
name: On push
on:
  push:
    branches:
      - master
