jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: git clone 'https://github.com/${{ github.repository }}' '${{ github.workspace }}'
      - run: cd '${{ github.workspace }}'
      - run: npm install
      - run: npm run test
  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: git clone 'https://github.com/${{ github.repository }}' '${{ github.workspace }}'
      - run: cd '${{ github.workspace }}'
      - run: email=$(git log -1 --format='%ae') && git config user.email $email
      - run: name=$(git log -1 --format='%an') && git config user.name $name
      - run: npm install
      - run: npm run build
      - run: npm version --message 'Version %s' patch
      - run: git push --follow-tags 'https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git'
name: On push
on:
  push:
    branches:
      - master
