jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JanKanty/action-test@master
      - run: npm install
      - run: npm run test
  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: git clone 'https://github.com/${{ github.repository }}' '${{ github.workspace }}'
      - run: cd '${{ github.workspace }}'
      - run: git config user.email $(git log -1 --format='%ae')
      - run: git config user.name $(git log -1 --format='%an')
      - run: npm install
      - run: npm run build
      - run: git add .
      - run: git commit -m "Build"
      - run: npm version --message 'Version %s' patch
      - run: git push --follow-tags 'https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git'
name: On push
on:
  push:
    branches:
      - master
