jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: git clone 'https://github.com/${{ github.repository }}' '${{ github.workspace }}'
      - run: cd '${{ github.workspace }}'
      - run: npm install
      - run: npm run test
  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email 'actions@github.com'
      - run: git config --global user.name 'GitHub actions'
      - run: git clone 'https://github.com/${{ github.repository }}' '${{ github.workspace }}'
      - run: cd '${{ github.workspace }}'
      - run: npm install
      - run: npm run build
      - run: npm version --message 'Version %s' patch
      - run: git push 'https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git'
name: On push
on:
  push:
    branches:
      - master
