jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: git init $GITHUB_WORKSPACE
      - run: git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
      - run: cd $GITHUB_WORKSPACE
      - run: npm install
  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: npm version --message "Version %s" patch
name: On push
on:
  push:
    branches:
      - master
